"""Import real product captures from the Orb repo into this site.

Reads docs/website-assets/screenshots in the Orb checkout (2x PNG screenshots
from capture.cjs) and writes:
  public/orb/screens/<theme>/<name>.webp module screenshots (1512 px wide, both themes)
  src/data/orbCaptures.ts               screen titles and heights, typed

Only the screens the pages show are imported (SCREENS below). The workflow
frames under docs/website-assets/frames are no longer imported: the site draws
its workflows itself (src/data/widgetFlows.ts), so public/orb/flows is gone.

Usage: python3 scripts/import_orb_assets.py [/path/to/Orb]
Needs Pillow (the Orb server venv has it).
"""
import json, os, sys
from pathlib import Path
from PIL import Image

ORB = Path(sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser('~/Documents/Projects/Orb'))
SRC = ORB / 'docs' / 'website-assets'
SITE = Path(__file__).resolve().parents[1]
OUT_SCREENS = SITE / 'public' / 'orb' / 'screens'
WIDTH = 1512

# Screens the site shows (name -> short title). Each must be registered in a
# module page's shots (src/data/modulePages.ts) or on the Security page; anything
# not listed here is not copied, so nothing unreferenced ships in dist.
SCREENS = {
    'nurse-my-shift': 'Nurse mode: what is due now',
    'nurse-observations-news2-live': 'Nurse mode: NEWS2 computed as the values go in',
    'orders-sepsis-six': 'Orders: Sepsis Six with the allergy interlock',
    'relay-case-rooms': 'Relay: case rooms',
    'sage-panel': 'Sage',
    'bridge-patient-portal': 'Bridge: the patient portal',
    'bridge-medications': 'Bridge: my medications',
    'bridge-documents': 'Bridge: my documents',
    'admin-trust': 'Admin: Trust Center',
    'admin-flight': 'Admin: Flight Recorder',
}

# Held back until recapture, 4 Oct 2026. Their pixels carry words the site does
# not use (tiles and trend labels the wording rules exclude, a bundle started
# by the score, the typed-name check's helper line, a stock column, an en dash,
# AUTO INTELLIGENCE badges, a six-ward scorecard, two models described in the
# old words, an NKDA handover for a patient with an anaphylaxis). A
# product-string sweep and recapture is queued; when the new captures are clean,
# move each line back into SCREENS and restore its shot line in modulePages.ts.
HELD_BACK = {
    'vigil-patient-board': 'Vigil: the ward ordered by NEWS2',
    'vigil-patient-story': 'Patient Story: one clinical narrative',
    'nurse-administer-medication': 'Nurse mode: administering a dose',
    'pharmacy-formulary': 'Helix: formulary',
    'relay-case-room': 'Relay: a case room with Vigil alerts inline',
    'admin-models': 'Admin: Model Governance',
    'admin-scorecard': 'Admin: Evaluation scorecard',
    'nurse-handover-ipass': 'Nurse mode: I-PASS handover draft',
}

# Crops applied after the resize, in pixels at 1512 wide: (top, bottom). The
# admin captures lose the tab strip that names a scorecard, the Trust Center
# loses the product's intro paragraph above its card, and both end above the
# floating control at the foot of the page. The numbers below are the boxes on
# the captures shipped on 4 Oct 2026 (1024 tall after resize); check them
# against a fresh capture before trusting them, since the layout may move.
CROPS = {
    'admin-trust': (255, 944),
    'admin-flight': (174, 863),
    # The 4 Oct 2026 capture: from the model's labelled note down to the end of
    # the scoring card, above a section the page printed twice (bug reported).
    'vigil-news2-explained': (158, 778),
    # The queue holds two rows; the frame ends under the table instead of showing half a page of nothing.
    'pharmacy-verify-queue': (0, 560),
    # Below the admin tab strip, which names a scorecard the site does not claim.
    'admin-data': (180, 790),
    'admin-audit': (112, 930),
}

def to_webp(src: Path, dst: Path, quality: int, crop=None) -> tuple[int, int]:
    im = Image.open(src).convert('RGB')
    if im.width > WIDTH:
        im = im.resize((WIDTH, round(im.height * WIDTH / im.width)), Image.LANCZOS)
    if crop:
        im = im.crop((0, crop[0], im.width, crop[1]))
    dst.parent.mkdir(parents=True, exist_ok=True)
    im.save(dst, 'WEBP', quality=quality, method=6)
    return dst.stat().st_size, im.height

screens = {}
total = 0
for theme in ('dark', 'light'):
    for name, title in SCREENS.items():
        src = SRC / 'screenshots' / theme / f'{name}.png'
        if not src.exists():
            print('  missing', theme, name); continue
        dst = OUT_SCREENS / theme / f'{name}.webp'
        size, height = to_webp(src, dst, 82, CROPS.get(name))
        total += size
        screens.setdefault(name, {'title': title})
        screens[name][theme] = f'/orb/screens/{theme}/{name}.webp'
        screens[name]['height'] = height
print(f'screens: {len(screens)} x 2 themes, {total/1e6:.1f} MB')

ts = ['// GENERATED by scripts/import_orb_assets.py from the Orb repo. Do not edit by hand.',
      '// Real screens of a running Orb appliance on seeded demo data (nothing is mocked up).',
      '// Only the captures the pages show are here; the held-back ones return after recapture.',
      'export interface Screen { title: string; dark: string; light: string; height: number }',
      f'export const SCREENS: Record<string, Screen> = {json.dumps(screens, indent=2, ensure_ascii=False)}',
      '']
(SITE / 'src' / 'data' / 'orbCaptures.ts').write_text('\n'.join(ts))
print('wrote src/data/orbCaptures.ts')
