// GENERATED by scripts/import_orb_assets.py from the Orb repo. Do not edit by hand.
// Real screens of a running Orb appliance on seeded demo data (nothing is mocked up).
export interface FlowStep { n: number; caption: string; src: string; hold: number }
export interface Flow { id: string; title: string; subtitle: string; user: string; steps: FlowStep[] }
export interface Screen { title: string; dark: string; light: string }
export const FLOWS: Flow[] = [
  {
    "id": "ward-is-alive",
    "title": "The ward watches itself",
    "subtitle": "Live vitals, NEWS2 ordering, and a chart that explains its own score",
    "user": "DOC001",
    "steps": [
      {
        "n": 1,
        "caption": "Sign in as a doctor. Orb Today lists what needs you first: deteriorating patients, new results, pending signatures.",
        "src": "/orb/flows/ward-is-alive/01.webp",
        "hold": 3200
      },
      {
        "n": 2,
        "caption": "Patients: the ward ordered by risk. Vitals move because a monitor feed is running; the order is NEWS2-derived, not hand-placed.",
        "src": "/orb/flows/ward-is-alive/02.webp",
        "hold": 3200
      },
      {
        "n": 3,
        "caption": "Open a chart. The NEWS2 band is computed by Orb's deterministic engine, never by a model.",
        "src": "/orb/flows/ward-is-alive/03.webp",
        "hold": 3200
      },
      {
        "n": 4,
        "caption": "Why this score? Every parameter's contribution is shown. Orb will not give you a number without showing where it came from.",
        "src": "/orb/flows/ward-is-alive/04.webp",
        "hold": 3200
      },
      {
        "n": 5,
        "caption": "Patient Story: alerts, notes, doses given, handovers and bundles in one scrollable narrative, with a bookmark for what is new since you last looked.",
        "src": "/orb/flows/ward-is-alive/05.webp",
        "hold": 4200
      }
    ]
  },
  {
    "id": "allergy-interlock",
    "title": "The allergy interlock",
    "subtitle": "A sepsis bundle is applied whole or not at all",
    "user": "DOC001",
    "steps": [
      {
        "n": 1,
        "caption": "Orders, then Order sets: cited protocols. Every item still goes through the allergy interlock, the dose guard and terminology validation.",
        "src": "/orb/flows/allergy-interlock/01.webp",
        "hold": 3200
      },
      {
        "n": 2,
        "caption": "Pick Sepsis Six. The gates are patient-specific, so there is nothing honest to show until Orb knows whose chart this is.",
        "src": "/orb/flows/allergy-interlock/02.webp",
        "hold": 3200
      },
      {
        "n": 3,
        "caption": "Apply to Suresh Reddy, 55, community-acquired pneumonia with early sepsis.",
        "src": "/orb/flows/allergy-interlock/03.webp",
        "hold": 3200
      },
      {
        "n": 4,
        "caption": "Eight items clear. Ceftriaxone is STOPPED: a documented anaphylaxis to IV ceftriaxone in 2023. The Apply button is disabled, because a half-applied sepsis bundle is its own emergency.",
        "src": "/orb/flows/allergy-interlock/04.webp",
        "hold": 5000
      },
      {
        "n": 5,
        "caption": "Same set, different patient: Ananya Kapoor has a moderate penicillin rash. Orb raises a cross-reactivity alert but does not block. Four patients, four different answers.",
        "src": "/orb/flows/allergy-interlock/05.webp",
        "hold": 4500
      }
    ]
  },
  {
    "id": "wrong-room-warning",
    "title": "The wrong-room warning",
    "subtitle": "Wrong patient, right ward: the most common serious error, caught without a modal",
    "user": "DOC001",
    "steps": [
      {
        "n": 1,
        "caption": "Messages: every patient has a case room. Open Suresh Reddy's.",
        "src": "/orb/flows/wrong-room-warning/01.webp",
        "hold": 3200
      },
      {
        "n": 2,
        "caption": "Type an order about a different patient into this room: \"Give Rajesh Iyer 40mg prednisolone now.\"",
        "src": "/orb/flows/wrong-room-warning/02.webp",
        "hold": 3200
      },
      {
        "n": 3,
        "caption": "Sent, not blocked. A nurse mid-emergency does not need a modal. Orb delivers it and says: this looks like it belongs to Rajesh Iyer, want me to move it?",
        "src": "/orb/flows/wrong-room-warning/03.webp",
        "hold": 5000
      }
    ]
  },
  {
    "id": "sage-ask",
    "title": "Ask Sage",
    "subtitle": "A local 27B model that cites what it read, on a box with no internet",
    "user": "DOC001",
    "steps": [
      {
        "n": 1,
        "caption": "Sage runs entirely on the appliance. No PHI leaves the box.",
        "src": "/orb/flows/sage-ask/01.webp",
        "hold": 3200
      },
      {
        "n": 2,
        "caption": "Fast mode answers general questions with the small model. Patient, medication and dose questions still go to the careful model. That floor is not a toggle in the UI.",
        "src": "/orb/flows/sage-ask/02.webp",
        "hold": 3200
      },
      {
        "n": 3,
        "caption": "Ask: what are the classic ECG findings in hyperkalaemia?",
        "src": "/orb/flows/sage-ask/03.webp",
        "hold": 3200
      },
      {
        "n": 4,
        "caption": "The answer, with a safety line inline and the guidelines it retrieved listed under \"Show details\".",
        "src": "/orb/flows/sage-ask/04.webp",
        "hold": 6000
      }
    ]
  },
  {
    "id": "sage-refusal",
    "title": "The cross-department refusal",
    "subtitle": "A real doctor with a real login, and Orb still says no",
    "user": "DOC001",
    "steps": [
      {
        "n": 1,
        "caption": "New chat. This login is General Medicine; cardiology is not its ward.",
        "src": "/orb/flows/sage-refusal/01.webp",
        "hold": 3200
      },
      {
        "n": 2,
        "caption": "Ask for the potassium result of the patient in cardiology bed C-201.",
        "src": "/orb/flows/sage-refusal/02.webp",
        "hold": 3200
      },
      {
        "n": 3,
        "caption": "No result. The cardiology chart is outside this login's scope, so Sage is never shown it. Scoping is enforced in the server, not hidden in the UI: a direct API call for that chart returns 404, as if the patient were not there at all.",
        "src": "/orb/flows/sage-refusal/03.webp",
        "hold": 6000
      }
    ]
  },
  {
    "id": "nurse-shift",
    "title": "The nurse's shift",
    "subtitle": "Same database, a different product: a list of what is due, and a score you see before you save",
    "user": "NUR001",
    "steps": [
      {
        "n": 1,
        "caption": "A nurse lands on My Shift, not on a chart: medications and observations due now, each with how late it is.",
        "src": "/orb/flows/nurse-shift/01.webp",
        "hold": 3200
      },
      {
        "n": 2,
        "caption": "My patients: the ward as this nurse owns it.",
        "src": "/orb/flows/nurse-shift/02.webp",
        "hold": 3200
      },
      {
        "n": 3,
        "caption": "Record observations: big numeric targets built for a tablet on a trolley.",
        "src": "/orb/flows/nurse-shift/03.webp",
        "hold": 3200
      },
      {
        "n": 4,
        "caption": "NEWS2 computes live as the values go in, with the RCP escalation sentence underneath. She sees what she is about to trigger before she saves it.",
        "src": "/orb/flows/nurse-shift/04.webp",
        "hold": 5000
      },
      {
        "n": 5,
        "caption": "Handover: an I-PASS draft written from recorded data, to be read against the patient before handing over.",
        "src": "/orb/flows/nurse-shift/05.webp",
        "hold": 4500
      }
    ]
  },
  {
    "id": "show-your-work",
    "title": "Show your work",
    "subtitle": "Live compliance posture, a tamper-evident audit chain, and an honest model register",
    "user": "ADM001",
    "steps": [
      {
        "n": 1,
        "caption": "Trust Center: compliance posture aggregated from the running system, not a PDF. Amber is amber; an all-green screen should be trusted less.",
        "src": "/orb/flows/show-your-work/01.webp",
        "hold": 3200
      },
      {
        "n": 2,
        "caption": "Flight Recorder: a SHA-256 hash chain over every audit row. Alter or delete one and the chain breaks. Every question Sage was asked is in there, and every refusal.",
        "src": "/orb/flows/show-your-work/02.webp",
        "hold": 3200
      },
      {
        "n": 3,
        "caption": "Model Governance: each model, its version, and whether it has been validated. The forecast model says \"untrained\". The validated one is the deterministic score that drives escalation.",
        "src": "/orb/flows/show-your-work/03.webp",
        "hold": 5000
      },
      {
        "n": 4,
        "caption": "Pilot Scorecard: how the pilot will be measured. Shadow-mode episodes, adjudication, outcomes, denominators included.",
        "src": "/orb/flows/show-your-work/04.webp",
        "hold": 4500
      }
    ]
  },
  {
    "id": "scribe-note",
    "title": "Scribe",
    "subtitle": "Dictation to a structured, verified note, on-device",
    "user": "DOC001",
    "steps": [
      {
        "n": 1,
        "caption": "Scribe: dictate or type. Nothing is sent to a cloud transcription service.",
        "src": "/orb/flows/scribe-note/01.webp",
        "hold": 3200
      },
      {
        "n": 2,
        "caption": "Pick the patient, then the free-text consultation goes in.",
        "src": "/orb/flows/scribe-note/02.webp",
        "hold": 3200
      },
      {
        "n": 3,
        "caption": "Structure Note: the local model drafts a SOAP note, then a second pass checks it against the transcript for unsupported claims and omissions before anyone signs it.",
        "src": "/orb/flows/scribe-note/03.webp",
        "hold": 6000
      },
      {
        "n": 4,
        "caption": "Sign & Finalize. This note was typed, never verified against audio, so Orb stops and makes the clinician type SIGN: accepting an unverified AI note is recorded in their own name.",
        "src": "/orb/flows/scribe-note/04.webp",
        "hold": 4500
      },
      {
        "n": 5,
        "caption": "Signed. Signing is the trigger: medications named in the note are extracted, screened, and queued for a pharmacist before they become active orders.",
        "src": "/orb/flows/scribe-note/05.webp",
        "hold": 5000
      }
    ]
  },
  {
    "id": "pharmacy-verify",
    "title": "Pharmacist verification",
    "subtitle": "Nothing AI-extracted is given until a pharmacist has verified it",
    "user": "PHA001",
    "steps": [
      {
        "n": 1,
        "caption": "Helix: the pharmacy overview.",
        "src": "/orb/flows/pharmacy-verify/01.webp",
        "hold": 3200
      },
      {
        "n": 2,
        "caption": "The verify queue: medications extracted from signed notes wait here for a pharmacist before they become active orders. Each is run against the interaction knowledge base; when a drug is outside it, Orb says NOT SCREENED instead of pretending.",
        "src": "/orb/flows/pharmacy-verify/02.webp",
        "hold": 3200
      },
      {
        "n": 3,
        "caption": "One row per extracted medication: dose, route and frequency editable, the source marked AI EXTRACTED, the safety line in plain words. Verify or Reject, and either decision is on the record in the pharmacist's name.",
        "src": "/orb/flows/pharmacy-verify/03.webp",
        "hold": 4500
      }
    ]
  },
  {
    "id": "patient-portal",
    "title": "Bridge, the patient portal",
    "subtitle": "The patient sees their own care in plain language",
    "user": "P001",
    "steps": [
      {
        "n": 1,
        "caption": "Bridge: care team, medications, results and documents for the patient, with a one-time login issued at admission.",
        "src": "/orb/flows/patient-portal/01.webp",
        "hold": 3200
      },
      {
        "n": 2,
        "caption": "Ask a question in plain language. The answer is scoped to this patient and never gives medical advice; it points back to the nurse or doctor.",
        "src": "/orb/flows/patient-portal/02.webp",
        "hold": 5000
      }
    ]
  }
]
export const SCREENS: Record<string, Screen> = {
  "today-doctor-home": {
    "title": "Today: the doctor home screen",
    "dark": "/orb/screens/dark/today-doctor-home.webp",
    "light": "/orb/screens/light/today-doctor-home.webp"
  },
  "vigil-patient-board": {
    "title": "Vigil: the ward ordered by NEWS2",
    "dark": "/orb/screens/dark/vigil-patient-board.webp",
    "light": "/orb/screens/light/vigil-patient-board.webp"
  },
  "vigil-patient-chart": {
    "title": "Vigil: a chart with live vitals and the Sepsis Six clock",
    "dark": "/orb/screens/dark/vigil-patient-chart.webp",
    "light": "/orb/screens/light/vigil-patient-chart.webp"
  },
  "vigil-news2-explained": {
    "title": "Vigil: every NEWS2 point explained",
    "dark": "/orb/screens/dark/vigil-news2-explained.webp",
    "light": "/orb/screens/light/vigil-news2-explained.webp"
  },
  "vigil-patient-story": {
    "title": "Patient Story: one clinical narrative",
    "dark": "/orb/screens/dark/vigil-patient-story.webp",
    "light": "/orb/screens/light/vigil-patient-story.webp"
  },
  "vigil-medications-emar": {
    "title": "Medications and eMAR from the chart",
    "dark": "/orb/screens/dark/vigil-medications-emar.webp",
    "light": "/orb/screens/light/vigil-medications-emar.webp"
  },
  "ward-round": {
    "title": "Ward round",
    "dark": "/orb/screens/dark/ward-round.webp",
    "light": "/orb/screens/light/ward-round.webp"
  },
  "nurse-my-shift": {
    "title": "Nurse mode: what is due now",
    "dark": "/orb/screens/dark/nurse-my-shift.webp",
    "light": "/orb/screens/light/nurse-my-shift.webp"
  },
  "nurse-observations-news2-live": {
    "title": "Nurse mode: NEWS2 computed as the values go in",
    "dark": "/orb/screens/dark/nurse-observations-news2-live.webp",
    "light": "/orb/screens/light/nurse-observations-news2-live.webp"
  },
  "nurse-administer-medication": {
    "title": "Nurse mode: administering a dose",
    "dark": "/orb/screens/dark/nurse-administer-medication.webp",
    "light": "/orb/screens/light/nurse-administer-medication.webp"
  },
  "nurse-handover-ipass": {
    "title": "Nurse mode: I-PASS handover draft",
    "dark": "/orb/screens/dark/nurse-handover-ipass.webp",
    "light": "/orb/screens/light/nurse-handover-ipass.webp"
  },
  "orders-cpoe": {
    "title": "Orders: lab, imaging and procedure orders",
    "dark": "/orb/screens/dark/orders-cpoe.webp",
    "light": "/orb/screens/light/orders-cpoe.webp"
  },
  "orders-order-sets": {
    "title": "Orders: cited order sets",
    "dark": "/orb/screens/dark/orders-order-sets.webp",
    "light": "/orb/screens/light/orders-order-sets.webp"
  },
  "orders-sepsis-six": {
    "title": "Orders: Sepsis Six with the allergy interlock",
    "dark": "/orb/screens/dark/orders-sepsis-six.webp",
    "light": "/orb/screens/light/orders-sepsis-six.webp"
  },
  "relay-case-rooms": {
    "title": "Relay: case rooms",
    "dark": "/orb/screens/dark/relay-case-rooms.webp",
    "light": "/orb/screens/light/relay-case-rooms.webp"
  },
  "relay-case-room": {
    "title": "Relay: a case room with Vigil alerts inline",
    "dark": "/orb/screens/dark/relay-case-room.webp",
    "light": "/orb/screens/light/relay-case-room.webp"
  },
  "sage-panel": {
    "title": "Sage",
    "dark": "/orb/screens/dark/sage-panel.webp",
    "light": "/orb/screens/light/sage-panel.webp"
  },
  "scribe": {
    "title": "Scribe",
    "dark": "/orb/screens/dark/scribe.webp",
    "light": "/orb/screens/light/scribe.webp"
  },
  "lens": {
    "title": "Lens",
    "dark": "/orb/screens/dark/lens.webp",
    "light": "/orb/screens/light/lens.webp"
  },
  "forecast-census": {
    "title": "Forecast: census",
    "dark": "/orb/screens/dark/forecast-census.webp",
    "light": "/orb/screens/light/forecast-census.webp"
  },
  "forecast-capacity": {
    "title": "Forecast: ward capacity",
    "dark": "/orb/screens/dark/forecast-capacity.webp",
    "light": "/orb/screens/light/forecast-capacity.webp"
  },
  "forecast-discharge-board": {
    "title": "Forecast: discharge board",
    "dark": "/orb/screens/dark/forecast-discharge-board.webp",
    "light": "/orb/screens/light/forecast-discharge-board.webp"
  },
  "command-center": {
    "title": "Command Center",
    "dark": "/orb/screens/dark/command-center.webp",
    "light": "/orb/screens/light/command-center.webp"
  },
  "capacity-simulator": {
    "title": "Surge Simulator",
    "dark": "/orb/screens/dark/capacity-simulator.webp",
    "light": "/orb/screens/light/capacity-simulator.webp"
  },
  "revenue-integrity": {
    "title": "Revenue Integrity",
    "dark": "/orb/screens/dark/revenue-integrity.webp",
    "light": "/orb/screens/light/revenue-integrity.webp"
  },
  "appointments": {
    "title": "Appointments",
    "dark": "/orb/screens/dark/appointments.webp",
    "light": "/orb/screens/light/appointments.webp"
  },
  "dietary": {
    "title": "Diet and Kitchen",
    "dark": "/orb/screens/dark/dietary.webp",
    "light": "/orb/screens/light/dietary.webp"
  },
  "pulse-environmental": {
    "title": "Pulse: environmental signals",
    "dark": "/orb/screens/dark/pulse-environmental.webp",
    "light": "/orb/screens/light/pulse-environmental.webp"
  },
  "surgical-suite-schedule": {
    "title": "Surgical Suite: schedule",
    "dark": "/orb/screens/dark/surgical-suite-schedule.webp",
    "light": "/orb/screens/light/surgical-suite-schedule.webp"
  },
  "surgical-suite-day": {
    "title": "Surgical Suite: the day",
    "dark": "/orb/screens/dark/surgical-suite-day.webp",
    "light": "/orb/screens/light/surgical-suite-day.webp"
  },
  "surgical-suite-active-cases": {
    "title": "Surgical Suite: active cases",
    "dark": "/orb/screens/dark/surgical-suite-active-cases.webp",
    "light": "/orb/screens/light/surgical-suite-active-cases.webp"
  },
  "pharmacy-helix-overview": {
    "title": "Helix: pharmacy overview",
    "dark": "/orb/screens/dark/pharmacy-helix-overview.webp",
    "light": "/orb/screens/light/pharmacy-helix-overview.webp"
  },
  "pharmacy-verify-queue": {
    "title": "Helix: pharmacist verification queue",
    "dark": "/orb/screens/dark/pharmacy-verify-queue.webp",
    "light": "/orb/screens/light/pharmacy-verify-queue.webp"
  },
  "pharmacy-formulary": {
    "title": "Helix: formulary",
    "dark": "/orb/screens/dark/pharmacy-formulary.webp",
    "light": "/orb/screens/light/pharmacy-formulary.webp"
  },
  "bridge-patient-portal": {
    "title": "Bridge: the patient portal",
    "dark": "/orb/screens/dark/bridge-patient-portal.webp",
    "light": "/orb/screens/light/bridge-patient-portal.webp"
  },
  "bridge-medications": {
    "title": "Bridge: my medications",
    "dark": "/orb/screens/dark/bridge-medications.webp",
    "light": "/orb/screens/light/bridge-medications.webp"
  },
  "bridge-labs": {
    "title": "Bridge: my results",
    "dark": "/orb/screens/dark/bridge-labs.webp",
    "light": "/orb/screens/light/bridge-labs.webp"
  },
  "bridge-documents": {
    "title": "Bridge: my documents",
    "dark": "/orb/screens/dark/bridge-documents.webp",
    "light": "/orb/screens/light/bridge-documents.webp"
  },
  "admin-trust": {
    "title": "Admin: Trust Center",
    "dark": "/orb/screens/dark/admin-trust.webp",
    "light": "/orb/screens/light/admin-trust.webp"
  },
  "admin-flight": {
    "title": "Admin: Flight Recorder",
    "dark": "/orb/screens/dark/admin-flight.webp",
    "light": "/orb/screens/light/admin-flight.webp"
  },
  "admin-models": {
    "title": "Admin: Model Governance",
    "dark": "/orb/screens/dark/admin-models.webp",
    "light": "/orb/screens/light/admin-models.webp"
  },
  "admin-scorecard": {
    "title": "Admin: Pilot Scorecard",
    "dark": "/orb/screens/dark/admin-scorecard.webp",
    "light": "/orb/screens/light/admin-scorecard.webp"
  },
  "admin-security": {
    "title": "Admin: Security",
    "dark": "/orb/screens/dark/admin-security.webp",
    "light": "/orb/screens/light/admin-security.webp"
  },
  "admin-audit": {
    "title": "Admin: Audit logs",
    "dark": "/orb/screens/dark/admin-audit.webp",
    "light": "/orb/screens/light/admin-audit.webp"
  },
  "admin-users": {
    "title": "Admin: Users and roles",
    "dark": "/orb/screens/dark/admin-users.webp",
    "light": "/orb/screens/light/admin-users.webp"
  },
  "admin-data": {
    "title": "Admin: Data and backups",
    "dark": "/orb/screens/dark/admin-data.webp",
    "light": "/orb/screens/light/admin-data.webp"
  },
  "module-frontdesk": {
    "title": "Front Desk",
    "dark": "/orb/screens/dark/module-frontdesk.webp",
    "light": "/orb/screens/light/module-frontdesk.webp"
  },
  "module-billing": {
    "title": "Billing",
    "dark": "/orb/screens/dark/module-billing.webp",
    "light": "/orb/screens/light/module-billing.webp"
  },
  "module-payments": {
    "title": "Payments",
    "dark": "/orb/screens/dark/module-payments.webp",
    "light": "/orb/screens/light/module-payments.webp"
  },
  "module-payer": {
    "title": "Insurance and TPA",
    "dark": "/orb/screens/dark/module-payer.webp",
    "light": "/orb/screens/light/module-payer.webp"
  },
  "module-procurement": {
    "title": "Procurement",
    "dark": "/orb/screens/dark/module-procurement.webp",
    "light": "/orb/screens/light/module-procurement.webp"
  },
  "module-housekeeping": {
    "title": "Housekeeping",
    "dark": "/orb/screens/dark/module-housekeeping.webp",
    "light": "/orb/screens/light/module-housekeeping.webp"
  },
  "module-nabh": {
    "title": "NABH accreditation",
    "dark": "/orb/screens/dark/module-nabh.webp",
    "light": "/orb/screens/light/module-nabh.webp"
  },
  "module-abdm": {
    "title": "ABDM",
    "dark": "/orb/screens/dark/module-abdm.webp",
    "light": "/orb/screens/light/module-abdm.webp"
  },
  "module-workforce": {
    "title": "Workforce",
    "dark": "/orb/screens/dark/module-workforce.webp",
    "light": "/orb/screens/light/module-workforce.webp"
  },
  "module-biomedical": {
    "title": "Equipment",
    "dark": "/orb/screens/dark/module-biomedical.webp",
    "light": "/orb/screens/light/module-biomedical.webp"
  },
  "downtime-mode": {
    "title": "Downtime pack: the printable snapshot",
    "dark": "/orb/screens/dark/downtime-mode.webp",
    "light": "/orb/screens/light/downtime-mode.webp"
  },
  "handoff-ipass": {
    "title": "I-PASS handoff sheet",
    "dark": "/orb/screens/dark/handoff-ipass.webp",
    "light": "/orb/screens/light/handoff-ipass.webp"
  },
  "mfa-enrolment": {
    "title": "MFA enrolment",
    "dark": "/orb/screens/dark/mfa-enrolment.webp",
    "light": "/orb/screens/light/mfa-enrolment.webp"
  },
  "command-palette": {
    "title": "Command palette",
    "dark": "/orb/screens/dark/command-palette.webp",
    "light": "/orb/screens/light/command-palette.webp"
  },
  "login-staff": {
    "title": "Staff sign-in",
    "dark": "/orb/screens/dark/login-staff.webp",
    "light": "/orb/screens/light/login-staff.webp"
  }
}
export const flowById = (id: string): Flow => { const f = FLOWS.find(x => x.id === id); if (!f) throw new Error("unknown flow " + id); return f }
