// GENERATED by scripts/import_orb_assets.py from the Orb repo. Do not edit by hand.
// Real screens of a running Orb appliance on seeded demo data (nothing is mocked up).
// Only the captures the pages show are here; the held-back ones return after recapture.
export interface Screen { title: string; dark: string; light: string; height: number }
export const SCREENS: Record<string, Screen> = {
  "nurse-my-shift": {
    "title": "Nurse mode: what is due now",
    "dark": "/orb/screens/dark/nurse-my-shift.webp",
    "light": "/orb/screens/light/nurse-my-shift.webp",
    "height": 1024
  },
  "nurse-observations-news2-live": {
    "title": "Nurse mode: NEWS2 computed as the values go in",
    "dark": "/orb/screens/dark/nurse-observations-news2-live.webp",
    "light": "/orb/screens/light/nurse-observations-news2-live.webp",
    "height": 1024
  },
  "orders-sepsis-six": {
    "title": "Orders: Sepsis Six with the allergy interlock",
    "dark": "/orb/screens/dark/orders-sepsis-six.webp",
    "light": "/orb/screens/light/orders-sepsis-six.webp",
    "height": 1024
  },
  "relay-case-rooms": {
    "title": "Relay: case rooms",
    "dark": "/orb/screens/dark/relay-case-rooms.webp",
    "light": "/orb/screens/light/relay-case-rooms.webp",
    "height": 1024
  },
  "sage-panel": {
    "title": "Sage",
    "dark": "/orb/screens/dark/sage-panel.webp",
    "light": "/orb/screens/light/sage-panel.webp",
    "height": 1024
  },
  "bridge-patient-portal": {
    "title": "Bridge: the patient portal",
    "dark": "/orb/screens/dark/bridge-patient-portal.webp",
    "light": "/orb/screens/light/bridge-patient-portal.webp",
    "height": 1610
  },
  "bridge-medications": {
    "title": "Bridge: my medications",
    "dark": "/orb/screens/dark/bridge-medications.webp",
    "light": "/orb/screens/light/bridge-medications.webp",
    "height": 1024
  },
  "bridge-documents": {
    "title": "Bridge: my documents",
    "dark": "/orb/screens/dark/bridge-documents.webp",
    "light": "/orb/screens/light/bridge-documents.webp",
    "height": 1024
  },
  "admin-trust": {
    "title": "Admin: Trust Center",
    "dark": "/orb/screens/dark/admin-trust.webp",
    "light": "/orb/screens/light/admin-trust.webp",
    "height": 689
  },
  "admin-flight": {
    "title": "Admin: Flight Recorder",
    "dark": "/orb/screens/dark/admin-flight.webp",
    "light": "/orb/screens/light/admin-flight.webp",
    "height": 689
  }
}
